create_database_query = "CREATE DATABASE IF NOT EXISTS {} ENGINE = Atomic"

create_table_of_mary_placements_query = """CREATE TABLE IF NOT EXISTS {} (
    channel_id UInt8,
    connection_id UInt32,
    project_id UInt32,
    customer_xid LowCardinality(String),
    campaign_xid LowCardinality(String),
    placement_id UInt32,
    placement_name LowCardinality(String),
    placement_type LowCardinality(String),
    status LowCardinality(String),
    labels Array(LowCardinality(String)),
    utm_campaign String,
    utm_medium String,
    utm_source String,
    outer_synced_at DateTime64
) ENGINE ReplacingMergeTree()
    ORDER BY placement_id"""

create_table_of_mary_stats_query = """CREATE TABLE IF NOT EXISTS {} (
    channel_id UInt8,
    campaign_xid String,
    placement_id UInt32,
    placement_name LowCardinality(String),
    date Date,
    impressions UInt64,
    clicks UInt64,
    cost_fact Float32,
    cpc_fact Float32,
    cpm_fact Float32,
    ctr Float32,
    model_orders UInt64,
    orders UInt64,
    revenue Float32,
    revenue_model_orders Float32
) ENGINE MergeTree()
    ORDER BY (date, channel_id, campaign_xid, placement_id, placement_name)
    PARTITION BY date"""

create_table_of_mary_ad_stats_query = """CREATE TABLE IF NOT EXISTS {} (
    channel_id UInt8,
    campaign_xid String,
    placement_id UInt32,
    placement_name LowCardinality(String),
    adgroup_id UInt64,
    adgroup_name LowCardinality(String),
    ad_id UInt64,
    ad_name String,
    ad_head String,
    ad_head2 String,
    ad_head3 String,
    ad_text String,
    ad_text2 String,
    ad_format LowCardinality(String),
    date Date,
    
    impressions UInt64,
    clicks UInt64,
    cost Float32,
    cost_fact Float32,
    cpc_fact Float32,
    cpm_fact Float32,
    cpv_fact Float32,
    cpe_fact Float32,
    ctr Float32,
    cpc Float32,
    cpm Float32,
    cpv Float32,
    cpe Float32,
    model_orders UInt64,
    orders UInt64,
    revenue Float32,
    revenue_model_orders Float32,
    leads UInt64,
    link_clicks UInt64,
    group_clicks UInt64,
    post_likes UInt64,
    post_shares UInt64,
    follows UInt64,
    comments UInt64,
    join_rate UInt64,
    hides UInt64,
    reports UInt64,
    unsubscribes UInt64,
    reach UInt64,
    reach_total UInt64,
    reach_total_sum UInt64,
    reach_subscribers UInt64,
    viral_reach_total_sum UInt64,
    video_views_start UInt64,
    video_views_2_sec UInt64,
    video_views_3_sec UInt64,
    video_views_6_sec UInt64,
    video_views UInt64,
    video_view_rate Float32,
    engagements UInt64,
    engagement_rate Float32
) ENGINE MergeTree()
    ORDER BY (date, channel_id, campaign_xid, placement_id, placement_name, ad_id)
    PARTITION BY date"""
